import selectors
from collections.abc import Callable
from enum import IntFlag
from typing import Protocol


class Sink(Protocol):
    def write(self, data: bytes) -> None: ...
    def set_flow_control(
        self, *, on_pause: Callable[[], None], on_drain: Callable[[], None]
    ) -> None: ...


class Interest(IntFlag):
    READ = selectors.EVENT_READ
    WRITE = selectors.EVENT_WRITE


class EventLoopProtocol(Protocol):
    def register(self, task: Task) -> None: ...
    def unregister(self, task: Task) -> None: ...
    def modify(self, task: Task, interests: int) -> None: ...
    def stop(self) -> None: ...


class Task(Protocol):
    loop: EventLoopProtocol

    def fileno(self) -> int: ...
    def interests(self) -> int: ...
    def on_readable(self) -> None: ...
    def on_writable(self) -> None: ...
    def on_error(self, exc: BaseException) -> None: ...
    def on_close(self) -> None: ...
